kind: pipeline
type: docker
name: default

workspace:
  path: /build

steps:
- name: clean
  image: docker:latest
  commands:
  - docker stop top250 || true
  - docker rm top250 || true

- name: build
  image: docker:latest
  commands:
  - docker build . -t top250

- name: build
  image: docker:latest
  commands:
  - docker run -p 9001:4000 -e DATABASE_URL=$DATABASE_URL -p 9002:4000 --restart=unless-stopped --name top250 -d top250 

environment:
  DATABASE_URL: 
    from_secret: database_url 

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock