kind: pipeline
type: docker
name: default

workspace:
  path: /build

steps:
- name: clean
  image: docker:latest
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker stop top250 || true
  - docker rm top250 || true

- name: deploy
  image: docker:latest
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DATABASE_URL: 
      from_secret: database_url 
  commands:
  - docker-compose up -d 


volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock