version: '3'

services:
  top250:
    build: .
    ports:
      - 9002:4000
    environment:
      - DATABASE_URL
    networks:
      - web
    container_name: top250
      
networks:
  web:
    external: true
      

          
